[tool.poetry]
name = "tnfsh-course-table-converter"
version = "1.0.0"
description = "A course table converter for TNFSH"
authors = ["tobiichi3227 <cz1346219@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^3.0"
jinja2 = "^3.0"
xlrd = "^2.0.1"
