on: push
name: Build artifacts
jobs:
  build:
     strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]

     runs-on: ${{ matrix.os }}

     steps:
        - name: Check-out repository
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
           python-version: '3.13'

        - name: Setup Poetry
          run: |
            curl -sSL https://install.python-poetry.org | python3 -

        - name: Install your Dependencies
          run: |
           pip install -r requirements.txt --break-system-packages

        - name: Build Executable with Nuitka
          uses: Nuitka/Nuitka-Action@main
          with:
           nuitka-version: main
           script-name: server.py
           # many more Nuitka options available, see action doc, but it's best
           # to use nuitka-project: options in your code, so e.g. you can make
           # a difference for macOS and create an app bundle there.
           mode: standalone
           include-data-dir: templates=templates

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
           name: ${{ runner.os }} Build
           path: | # match what's created for the 3 OSes
              build/*.dist/*
              build/*.dist/*
