on: push
name: Build artifacts
jobs:
  build:
     strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]

     runs-on: ${{ matrix.os }}

     steps:
        - name: Check-out repository
          uses: actions/checkout@v4

        - name: Setup Golang
          uses: actions/setup-go@v5
          with:
           go-version: '>=1.24.0'

        - name: Build Executable
          run: go build -ldflags='-s -w'

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
           name: ${{ runner.os }} Build
           path: | # match what's created for the 3 OSes
            tnfsh-course-table-converter*
